version: "3.9"

services:
  api:
    build: .
    container_name: votesync_api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./FrontEnd:/app/FrontEnd
    environment:
      DATABASE_URL: "postgresql+psycopg://postgres:${dbPassword}@db:5432/${db_name}"
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: votesync_db
    restart: always
    environment:
      POSTGRES_USER: ${dbUser}
      POSTGRES_PASSWORD: ${dbPassword}
      POSTGRES_DB: ${db_name}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
